taksify/lib/takso_web/router.ex
defmodule TaksoWeb.Router do
  use TaksoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug CORSPlug, origin: "*"
    plug :accepts, ["json"]
  end

  scope "/", TaksoWeb do
    pipe_through :browser # Use the default browser stack
    get "/", CustomerController, :landing
    get "/login", CustomerController, :login
    get "/booking",CustomerController , :booking
    resources "/users", UserController
    resources "/bookings", BookingController

  end

  # Other scopes may use custom stacks.
  scope "/api", TaksoWeb do
    pipe_through :api

    post "/bookings", Api.BookingController, :create
    post "/sessions", Api.SessionController, :create
    post "/addTaxi", Api.TaxiController, :create
  end

  scope "/api/bookings", TaksoWeb do
    pipe_through :api

    post "/create", Api.BookingController, :create
    post "/delete", Api.BookingController, :delete
    #post "/update", Api.BookingController, :update
    #post "/show", Api.BookingController, :show
  end

  scope "/api/users", TaksoWeb do
    pipe_through :api

    post "/create", Api.UserController, :create
    post "/delete", Api.UserController, :delete
    post "/update", Api.UserController, :update
    post "/show", Api.UserController, :show
  end

end

taksify/lib/takso_web/controllers/customer_controller.ex
defmodule TaksoWeb.CustomerController do
  use TaksoWeb, :controller

  def landing(conn, _params) do
    render conn, "landing.html"
  end

  def login(conn, _params) do
    render conn, "login.html"
  end

  def booking(conn, _params) do
    render conn, "booking.html"
  end
  
end

taksify/lib/takso_web/views/customer_view.ex
defmodule TaksoWeb.CustomerView do
  use TaksoWeb, :view
end

taksify/lib/takso_web/templates/customer/booking.html.eex
<div id="takso-app">  
    <customer></customer>
</div>

taksify/lib/takso_web/templates/customer/landing.html.eex
<br/>
<p style="text-align:center;"><img src= "<%= static_path(@conn, "/images/phoenix.png")%>" class="img-fluid"/> </p> 

<div id="takso-app">
<landingpage></landingpage>
</div>
<br>
<div style="text-align:center;"> <%= link "login", to: customer_path(@conn, :login) %> </div>

  

taksify/lib/takso_web/templates/customer/login.html.eex
<div style="text-align:center;">
    <img src= "<%= static_path(@conn, "/images/taksifylogo.png")%>" class="img-fluid"/>
</div>
<div id="takso-app">    
    <login></login>
</div>
<div style="text-align:center;"> <%= link "go to booking page", to: customer_path(@conn, :booking) %> </div>